### ISSUE TITLE
Add ESLint to project

### ISSUE THREAD

**Issue by JingYenLoh** [sofiawong/SL_Node_Mongo_Express#1]
I would assume you are using VSCode to do the exercises. Please take the time to setup an ESLint config, preferably extending some popular config like standard or airbnb.

[This article](https://travishorn.com/setting-up-eslint-on-vs-code-with-airbnb-javascript-style-guide-6eb78a535ba6) may be useful.

**Comment by sofiawong** [comment]
I have added eslint to my project already
