### ISSUE TITLE
Practice branching & commit staging

### ISSUE THREAD

**Issue by francisyzy** [sofiawong/SL_Node_Mongo_Express#2]
You can take this opportunity to learn how to branch and merge when doing different exercises. This will keep your master branch tidy when the final work is produced.

If you are using [Visual Studio Code to manage GitHub](https://code.visualstudio.com/Docs/editor/versioncontrol#_git-support), you can easily stage changes to make git commit messages more meaningful.

_press the + icon_
![screen shot 2018-03-10 at 12 20 29 am](https://user-images.githubusercontent.com/24467184/37217645-0dbcd234-23f9-11e8-85a0-ec62d2aeef09.png)
![screen shot 2018-03-10 at 12 21 35 am](https://user-images.githubusercontent.com/24467184/37217646-0df5c490-23f9-11e8-8626-91449fde53d0.png)

**Comment by sofiawong** [comment]
Actually, I was using atom text editor. But I switched to vs code alr. Initially, I just put all the stuff on master branch cuz I couldnt think how to branch it. I will start a branch for week 2 of the course. Sorry for the wait.
